### PR TITLE
Buttons to empty activities

### PR DESCRIPTION
**Pull request by Saadnajmi**
Want to add: Real Icons, an actual Navigation Drawer..

### CODE REVIEW

**Comment by Saadnajmi** [comment]
Fixes #8

**Comment by zuhairp** [comment]
How easy would it be to switch to Navigation Drawer? Ideally we wouldn't work ourselves into a situation where refactoring will be a bitch

**Comment by Saadnajmi** [comment]
Naviagation Drawer uses fragments. Sooooo that would be some refactoring.

**Comment by zuhairp** [comment]
That might be too much technical debt, are navigation drawers that troublesome?

**Comment by Saadnajmi** [comment]
I haven't gotten it working. Despite having an example project that compiles with example code..
I was gonna make someone else do it so we aren't blocked

**Comment by zuhairp** [comment]
Abandon this?

**Pull request closed without merging**
