### PR TITLE
Acknowledgments android

### PR DESCRIPTION
**Pull request by xirothehero**
1) For TW/FB goes to web. Idk if that's just my phone or b/c idk how to filter intent for other apps
2) Icons not in other drawable-~~~ files

other than that i think it's ok

### CODE REVIEW

**Comment by Saadnajmi** [comment]
1) That's fine
2) That's fine. I'm only using one drawable folder too

**Comment by xirothehero** [comment]
3) Layout gets messed up in landscape orientation lol

**Comment by Saadnajmi** [comment]
Disable landscape app wide. There should be an easy way to do that

**Comment by Saadnajmi** [comment]
I got it

**Comment by zuhairp** [comment]
@xirothehero Can you attach a screenshot?

**Comment by Saadnajmi** [comment]
@zuhairp @xirothehero I'm about to compile it so I'll attach them (unless Ali was already on it)

**Comment by xirothehero** [comment]
I put a screenshot on Slack, gonna try something to lock orientation

**Comment by Saadnajmi** [comment]
screenshot_20170410-002641 1

This isn't too bad...

**Comment by xirothehero** [comment]
So should I commit the orientation lock stuff?

**Comment by zuhairp** [comment]
Yeah

**Comment by Saadnajmi** [comment]
@xirothehero Yeah. I'll let you do it

Also, delete :

D       mobile/Client/Client.Droid/Resources/layout/fragment_annoucements.axml
D       mobile/Client/Client.Droid/Screens/AnnoucmentsFragment.cs


Notice the mispelling in the name. They are leftover files

**Comment by zuhairp** [comment]
Also the url is msa-texas.org - I totally screwed that up in iOS... (it opens the right page though)

**Comment by Saadnajmi** [comment]
Reviewing

**Comment by xirothehero** [comment]
@saad ok I see dem. Is delete =/= remove?

**Comment by zuhairp** [comment]
Did you fix the URL?

**Comment by xirothehero** [comment]
@zuhairp yeah

**Comment by Saadnajmi** [comment]
@zuhairp forgot about that..

**Comment by zuhairp** [comment]
I see that you did

**Comment by xirothehero** [comment]
Also it says I'm not authorized to merge

**Comment by Saadnajmi** [comment]
jk.. I push the button then

**Pull request merged**
